#!/bin/bash

if [ ! -f ~/.aws/config ]; then
  if [ ! -f ~/.aws/credentials ]; then
    # Make sure the env vars are set
    if [ -z ${AWS_ACCESS_KEY_ID+x} ]; then
      echo "AWS_ACCESS_KEY_ID is not set"
      exit
    fi

    if [ -z ${AWS_SECRET_ACCESS_KEY+x} ]; then
      echo "AWS_SECRET_ACCESS_KEY is not set"
      exit
    fi
  fi
fi


if [ ! -f ~/.aws/config ]; then
  echo 'AWS Config File does not exist. Creating it...'

  mkdir -p ~/.aws
  touch  ~/.aws/config
  cat <<EOT >> ~/.aws/config
# ~/.aws/config

[profile claire]
region = us-west-2
output = json
EOT
fi

if [ ! -f ~/.aws/credentials ]; then
  echo 'AWS Credentials File does not exist. Creating it...'

  mkdir -p ~/.aws
  touch ~/.aws/credentials
  cat <<EOT >> ~/.aws/credentials
# ~/.aws/credentials

[claire]
aws_access_key_id = $AWS_ACCESS_KEY_ID
aws_secret_access_key = $AWS_SECRET_ACCESS_KEY
EOT
fi


if [ ! -f ~/.s3cmd ]; then
  echo 'S3 CMD File does not exist. Creating it...'

  mkdir -p ~/.aws
  touch ~/.aws/credentials
  cat <<EOT >> ~/.s3cmd
# ~/.s3cmd
[default]
access_key = $AWS_ACCESS_KEY_ID
access_token =
add_encoding_exts =
add_headers =
bucket_location = $aws_region
ca_certs_file =
cache_file =
check_ssl_certificate = True
check_ssl_hostname = True
cloudfront_host = cloudfront.amazonaws.com
default_mime_type = binary/octet-stream
delay_updates = False
delete_after = False
delete_after_fetch = False
delete_removed = False
dry_run = False
enable_multipart = True
encoding = UTF-8
encrypt = False
expiry_date =
expiry_days =
expiry_prefix =
follow_symlinks = False
force = False
get_continue = False
gpg_command = None
gpg_decrypt = %(gpg_command)s -d --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
gpg_encrypt = %(gpg_command)s -c --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
gpg_passphrase = claire
guess_mime_type = True
host_base = s3.amazonaws.com
host_bucket = %(bucket)s.s3.amazonaws.com
human_readable_sizes = False
invalidate_default_index_on_cf = False
invalidate_default_index_root_on_cf = True
invalidate_on_cf = False
kms_key =
limit = -1
limitrate = 0
list_md5 = False
log_target_prefix =
long_listing = False
max_delete = -1
mime_type =
multipart_chunk_size_mb = 15
multipart_max_chunks = 10000
preserve_attrs = True
progress_meter = True
proxy_host =
proxy_port = 0
put_continue = False
recursive = False
recv_chunk = 65536
reduced_redundancy = False
requester_pays = False
restore_days = 1
restore_priority = Standard
secret_key = $AWS_SECRET_ACCESS_KEY
send_chunk = 65536
server_side_encryption = False
signature_v2 = False
simpledb_host = sdb.amazonaws.com
skip_existing = False
socket_timeout = 300
stats = False
stop_on_error = False
storage_class =
urlencoding_mode = normal
use_http_expect = False
use_https = True
use_mime_magic = True
verbosity = WARNING
website_endpoint = http://%(bucket)s.s3-website-%(location)s.amazonaws.com/
website_error =
website_index = index.html
EOT
fi
